### ISSUE TITLE
Evaluate Synthetic Trained on Real

### ISSUE THREAD

**Issue by sheshappanavar** [hkust-vgd/scanobjectnn#16]
How to create the test "modelnet/modelnet_test.h5" file ?

I got the following error:
Traceback (most recent call last):
  File "evaluate_synthetic_trained_on_real.py", line 83, in <module>
    TEST_DATA, TEST_LABELS = data_utils.load_h5(TEST_FILE)
  File "/raid1/inprogress/ssheshap/Other/ForAWS/scanobjectnn/pointnet2/../data_utils.py", line 250, in load_h5
    f = h5py.File(h5_filename)
  File "/raid1/inprogress/ssheshap/software/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/raid1/inprogress/ssheshap/software/anaconda3/lib/python3.7/site-packages/h5py/_hl/files.py", line 195, in make_fid
    fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 105, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'modelnet/modelnet_test.h5', errno = 2, error message = 'No such file or directory', flags = 15, o_flags = c2)

**Comment by mikacuy** [comment]
Hi,

You can create the following h5 file using the modelnet40 objects from https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip

The object classses used for this experiment is described in the paper. Then this error should be resolved.

Best,
Mika
